### ISSUE TITLE
Support for login credentials

### ISSUE THREAD

**Issue by yozik04** [dubnom/pyhomeworks#5]
My HomeWorks 8 controller's Telnet port requires credentials
Upon connection it sends `LOGIN: ` prompt (no `\n` in the end)
I need to send `user,password\n` string to it
then it will reply with `login successful\n`
after that is OK to send setup and subscribe to events
`PROMPTOFF`
`KBMON`
`GSMON`
`DLMON`
`KLMON`

Are you accepting pull requests? I can try to implement that part myself. But will you be able to update that in HomeAssistant as well?

**Comment by kayvz** [comment]
@yozik04 Were you ever able to figure this out? Any tips?

**Comment by dubnom** [comment]
Pull requests are fine. What I would do is copy the project into the custom components area of your system and make mods there until it works.
- Mike

Sent from my iPad

On Apr 13, 2021, at 7:25 AM, Jevgeni Kiski ***@***.***> wrote:

﻿

My HomeWorks 8 controller's Telnet port requires credentials
Upon connection it sends LOGIN: prompt (no \n in the end)
I need to send user,password\n string to it
then it will reply with login successful\n
after that is OK to send setup and subscribe to events
PROMPTOFF
KBMON
GSMON
DLMON
KLMON

Are you accepting pull requests? I can try to implement that part myself. But will you be able to update that in HomeAssistant as well?

**Comment by yozik04** [comment]
> @yozik04 Were you ever able to figure this out? Any tips?

Yes I did. But I rewrote a lot. I also did conponent search but it is specific to the house.

**Comment by kayvz** [comment]
I have a map of all my components based on some manual telnet sleuthing, and I also have a Homeworks 8 system which requires telnet login prompt like you @yozik04 .

I think I’m getting stuck on configuring my NPort RS232<>Ethernet adapter properly. Would you mind sharing what configuration settings you used for the adapter (e.g. Telnet server or client, reverse telnet, baud rate, bits, hardware flow, etc)

**Comment by dubnom** [comment]
115200, none, 8, 1, RTS/CTS, enable
TCP server

Sent from my iPad

On Oct 22, 2022, at 10:00 AM, Kayvon Beykpour ***@***.***> wrote:

﻿

I have a map of all my components based on some manual telnet sleuthing, and I also have a Homeworks 8 system which requires telnet login prompt like you @yozik04<https://github.com/yozik04> .

I think I’m getting stuck on configuring my NPort RS232<>Ethernet adapter properly. Would you mind sharing what configuration settings you used for the adapter (e.g. Telnet server or client, reverse telnet, baud rate, buts, hardware flow, etc)

**Comment by kayvz** [comment]
thank you. @yozik04 I'm using your fork with the added authentication/login support and I'm wondering where I need to pass in my Lutron credentials. my telnet password is "jetski" because when I manually telnet into HW and do "login, jetski" I'm able to successfully connect the processor and observe all the activity from Lutron (dimmers changing, etc).

**Comment by dubnom** [comment]
I’m not sure. I’m about 1,000 miles away from my house at the moment. I’ll be back Monday.
I would turn on debugging for the component and see what is being sent by homeworks. I’m not sure if I left debug logging in, but it should be easy to add.

Sent from my iPhone

On Oct 22, 2022, at 1:22 PM, Kayvon Beykpour ***@***.***> wrote:

﻿

thank you. @yozik04<https://github.com/yozik04> I'm using your fork with the added authentication/login support and I'm wondering where I need to pass in my Lutron credentials. my telnet password is "jetski" because when I manually telnet into HW and do "login, jetski" I'm able to successfully connect the processor and observe all the activity from Lutron (dimmers changing, etc).

**Comment by yozik04** [comment]
@kayvz I think I have stopped pushing new changes to the repository and there is not finished state.

**Comment by kayvz** [comment]
I was able to get it to work! thanks so much
